"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var myShape = new Shape_1.Shape(10, 5);
console.log("Shape is: " + myShape.getInfo());
var myCircle = new Circle_1.Circle(10, 5, 3);
console.log("Circle is: " + myCircle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(10, 20, 75, 90);
console.log("Rectangle is: " + myRectangle.getInfo());
